name: Deploy Galaux API

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Execute remote ssh commands
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          script: |
            cd ~/www/galauxminecraftapi.ru/

            git pull origin main

            # composer install --no-dev --optimize-autoloader --no-interaction

            php artisan migrate --force

            php artisan optimize:clear

            php artisan config:cache
            php artisan route:cache

            # php artisan scramble:export
